# Info-201-final
# Readme

***

## Exploring the Relationship Between Median Income and Crime Rate in Seattle 

### Description


This project explores the relationship between economic status and crime within Seattle neighborhoods. The relationship was determined by analyzing rate of various crime  (e.g., robbery, burglary, and theft) in various areas of Seattle and comparing those crime rates to median household incomes in each area by zip code. Our goal is to find out if there is a pattern between them so that Seattle citizens and those considering moving to Seattle can have a better understanding of the relationship between median household income and crime rates as well as the safe areas of Seattle.

In this project, we analyzed the data using R and R Studio and the package "Tidyverse" and plotted the graphs using R and R Studio and the package "ggplot".


### Datasets

- **SPD Crime Data**: Crime data from the Seattle Police Department, from 2008 to present. Available at [Seattle Open Data Portal](https://data.seattle.gov/Public-Safety/SPD-Crime-Data-2008-Present/tazs-3rd5/data) 
- **Median Household Income**: Median household income information by zip code, up to date October 2023. Sourced from [Simple Maps - Seattle Income Data](https://simplemaps.com/city/seattle/zips/income-household-median)

### Install

To run this code, you need to install R. For viewing the result file, which is in HTML format, you will require a browser or another software that can open HTML files.

### Result

The analysis of the data shows that there is a positive weak correlation between median income of a zip code and the frequency of crimes in that zip code. This can be seen on the trendline of the following chart.

```{r}
library(magick)
img <- image_read("../info 201/Info 201 final/Info-201-final_files/Info 201 final chart.png")
plot(img)
```

### Author

WenHua Chen, August Altucher, Erhong Gao, Grace Harrill
